---
abstract: 'Base class and script for adding of book from NKC to Wikidata.'
author:
  - 'Michal Josef Spacek <skim@cpan.org>'
build_requires:
  English: 0
  ExtUtils::MakeMaker: 6.59
  File::Object: 0
  File::Spec::Functions: 0
  Test::More: 0
  Test::NoWarnings: 0
  Test::Output: 0
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.21'
license: bsd
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: App-NKC2Wikidata
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  Business::ISBN: 0
  Encode: 0
  Error::Pure: 0
  Getopt::Std: 0
  MARC::Convert::Wikidata: 0
  MARC::Record: 0
  WQS::SPARQL: 0
  WQS::SPARQL::Query::Count: 0
  WQS::SPARQL::Query::Select: 0
  WQS::SPARQL::Result: 0
  Wikibase::API: 0
  Wikibase::Cache: 0
  Wikibase::Datatype::Print::Item: 0
  Wikidata::Reconcilation::AudioBook: 0
  Wikidata::Reconcilation::BookSeries: 0
  Wikidata::Reconcilation::Periodical: 0
  Wikidata::Reconcilation::VersionEditionOrTranslation: 0
  ZOOM: 0
  perl: 5.6.0
resources:
  bugtracker: https://github.com/michal-josef-spacek/App-NKC2Wikidata/issues
  homepage: https://github.com/michal-josef-spacek/App-NKC2Wikidata
  license: http://opensource.org/licenses/bsd-license.php
  repository: git://github.com/michal-josef-spacek/App-NKC2Wikidata
version: '0.01'
